### ISSUE TITLE
Identical camera id's between proxied collections can be confusing

### ISSUE THREAD

**Issue by karlmacklin** [rgrams/rendercam#16]
I had an issue where I had a camera object with id camera in one collection, and then proxied in another collection which camera had the same id.

The result was that the camera didn't handle the scaling properly etc. Just changing the id of the second collection's camera fixed the problem.

So either that's something that could need looking over code-wise, or put up a disclaimer in the readme to avoid that.

**Comment by Tomires** [comment]
Seconded, encountered the same issue when migrating to Rendercam.

**Comment by rgrams** [comment]
Thanks guys, good catch! Yeah, right now the cameras are keyed by their ID, so if they are named the same and each in the base collection of their proxy (or your main collection), they'll conflict. The data from the second camera will overwrite the data from the first . . . :S For now I will add a disclaimer and an error message.

Do you guys think this is enough of a problem that I should change the code? The IDs are identical, so I would have to change the API a bit so all the functions take full URLs instead of just IDs.

**Comment by karlmacklin** [comment]
For me, just knowing not to use the same id solves it. Can't think of a situation where you dynamically create cameras and not be able to give them unique names either.

At the same time, I didn't really think about the id's at all first, and it'd be nicer to not have to. But not a dealbreaker.

**Comment by Tomires** [comment]
A mention of this issue in the documentation combined with a corresponding error message are enough I think.

**Comment by rgrams** [comment]
OK, done. Thanks guys! At some point I will see if I can find a way to completely remove this issue without changing the API, but for now I'll consider this closed.
