### ISSUE TITLE
A way to move camera and shake at the same time?

### ISSUE THREAD

**Issue by karlmacklin** [rgrams/rendercam#25]
In my space shooter I want to zoom in to the player's position when it dies.
So, I'm both changing the ortho scale and moving the camera itself by x/y-position. The move is by go.animate on the position of the camera game object.

I'd also like to apply camera shake during this transition. However, as soon as you animate the x/y-position you seem to nullify any shaking going on. It does kick in after the position animation if the shake has a longer duration however.

First I thought maybe a "shakeTo" method would be useful, but that's a bit too specific. Plus, how do you handle different durations between the shake and the position animation?

I realize this might be tricky to solve for the use case where you are animation the position via go.animate, but maybe there's a way to have a method on rendercam itself, like:

```
rendercam.shake(3, 0.6)
rendercam.moveTo(p, duration, easing)
```

or something like that? Then rendercam would of course itself have to handle the current transitioning somehow.. No idea how to solve it, but hey, here's a use case for it at least 😄

**Comment by subsoap** [comment]
You can write your own easing functions and apply screen shake amount to that over time. I've done this before and it works great.

**Comment by karlmacklin** [comment]
@subsoap Do you mean applying shake via rendercam.shake or to the position animation of the rendercam object?

**Comment by subsoap** [comment]
You use your custom easing function to apply the movement animation over time, and then apply the shake value to it before you set the camera position.

**Comment by rgrams** [comment]
Hmm, I admit I didn't test this with go.animate, though I'm not too surprised to hear that it works this way. The camera shake is applied in a "post-update"—the camera sends a message to itself every update and runs the code in the message response, so it's guaranteed to happen after all normal update() functions run. But I guess the engine updates animations after that. 

I think the easiest way to solve your problem is to stick your camera on another game object, and animate that.

**Comment by karlmacklin** [comment]
Yes of course! Definitely the easiest way right now. Closing issue.
