### ISSUE TITLE
Problem with pick node with arbitrary gui position

### ISSUE THREAD

**Issue by subsoap** [rgrams/rendercam#39]
What am I misunderstanding about how this should work?

Attached sample project, press wasd or mouse to move cursor position. When screen is not resized it works. When screen resizes it does not work. What am I missing?

![2020-02-24 18_20_50-GamepadGUITester](https://user-images.githubusercontent.com/409170/75209210-8f288480-5732-11ea-9d2d-06becf9f3c06.png)

[GamepadGUITester.zip](https://github.com/rgrams/rendercam/files/4247767/GamepadGUITester.zip)

```
local rendercam = require("rendercam.rendercam")

local move_speed = 10
local left = vmath.vector3(-1,0,0)
local right = vmath.vector3(1,0,0)
local up = vmath.vector3(0,1,0)
local down = vmath.vector3(0,-1,0)

local cursor_node
local button_node

local function check_button(self)
	local position = rendercam.world_to_screen(self.cursor_world_position, gui.ADJUST_FIT)
	local x, y = rendercam.screen_to_gui_pick(position.x, position.y)
	if gui.pick_node(button_node, position.x, position.y) then
		gui.set_color(button_node, vmath.vector4(0,1,0,1))
	else
		gui.set_color(button_node, vmath.vector4(1,0,0,1))
	end
end

local function update_cursor_position(self)
	local position = rendercam.world_to_screen(self.cursor_world_position, gui.ADJUST_FIT)
	gui.set_position(cursor_node, position)
	--print(self.cursor_world_position, position)
	check_button(self)
end


function init(self)
	cursor_node = gui.get_node("cursor")
	button_node = gui.get_node("button")
	
	msg.post(".", "acquire_input_focus")
	self.cursor_world_position = vmath.vector3(0,0,0)
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == nil then
		self.cursor_world_position = rendercam.screen_to_world_2d(action.screen_x, action.screen_y)
		update_cursor_position(self)
	end
	
	if action_id == hash("key_w") then
		self.cursor_world_position = self.cursor_world_position + up * move_speed
		update_cursor_position(self)
	end
	if action_id == hash("key_a") then
		self.cursor_world_position = self.cursor_world_position + left * move_speed
		update_cursor_position(self)
	end
	if action_id == hash("key_s") then
		self.cursor_world_position = self.cursor_world_position + down * move_speed
		update_cursor_position(self)
	end
	if action_id == hash("key_d") then
		self.cursor_world_position = self.cursor_world_position + right * move_speed
		update_cursor_position(self)
	end
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end

```

**Comment by rgrams** [comment]
That's quite the merry-go-round of transformations you have there! I checked it out a bit but haven't sorted out where exactly the problem is. But what exactly do you want to do? Do you want to control your gamepad cursor in world space (and be changed by camera zoom, etc.), or screen space? Or could it maybe be a gui node and maybe you wouldn't have to do any conversion at all?

**Comment by rgrams** [comment]
OK, so everything actually works, it's just that rendercam.world_to_screen actually does two different things, and its confusing. 

First off, there's three different coordinate systems. They're all the same if you don't change the window, but if you do then they're all different.
* Screen coordinates - Actual monitor pixels inside the window.
* Gui coordinates - Different for each adjust mode, what you get/use with gui.get_position & gui.set_position.
* Gui picking coordinates - What you need for gui.pick_node. Like action.x, action.y.

__rendercam.world_to_screen__
1. If you do _not_ give it an adjust mode, it converts world coordinates to _screen_ coordinates.
2. If you DO give it an adjust mode, it converts world coordinates to _gui_ coordinates.

For pick_node, you always need to use rendercam.screen_to_gui_pick with _screen_ coordinates (not gui coordinates).

For your example, replace your check_button function with this one:
```lua
local function check_button(self)
	local screenPos = rendercam.world_to_screen(self.cursor_world_position) -- No adjust mode!
	local pickX, pickY = rendercam.screen_to_gui_pick(screenPos.x, screenPos.y)
	if gui.pick_node(button_node, pickX, pickY) then
		gui.set_color(button_node, vmath.vector4(0,1,0,1))
	else
		gui.set_color(button_node, vmath.vector4(1,0,0,1))
	end
end
```
(also, you had a goof in yours, you used position.x/y with pick_node instead of the x/y that you converted.)

**Comment by rgrams** [comment]
I will see about tweaking the documentation for world_to_screen(), or possibly splitting it into two functions so it's not as confusing.

**Comment by subsoap** [comment]
> That's quite the merry-go-round of transformations you have there! I checked it out a bit but haven't sorted out where exactly the problem is. But what exactly do you want to do? Do you want to control your gamepad cursor in world space (to be changed by camera zoom, etc.), or screen space? Or could it maybe be a gui node and maybe you wouldn't have to do any conversion at all?

Basically I wanted to have a gamepad move a GUI node and have its position able to pick other GUI nodes. I tried various things to see if they would work but eventually gave up and came for help. 😇

Thank you for the fix, it works! 🍀

**Comment by rgrams** [comment]
OK, you don't have to do so much work for just that. I did another little test to be sure. You can use a gui node with "stretch" mode as your cursor and just use it's position directly with gui.pick_node. You can make that node invisible and give it a child node with "fit" mode for the graphic (presumably you don't want your cursor to stretch). If you also want to set its position to the mouse, you just have to do rendercam.screen_to_gui with the mouse screen pos.

**Comment by subsoap** [comment]
I should have been more clear, what I wanted to do was make it work with pick node and with GOs in the world space. Thank you for your help! You should start a patreon, if you do I'll support you there.

**Comment by rgrams** [comment]
Ahh, gotcha. In that case I would probably store your cursor position in screen coordinates. That way you can just as easily set it with the mouse pos or modify it with gamepad inputs, it's just one function call to convert it to GUI coords or to world coords, and it'll never be affected by anything weird you might do with your cameras (or build up precision issues or anything like that).

No problem, thanks! Good luck with your project!
